### ISSUE TITLE
有没有umeng反馈android团队的人？

### ISSUE THREAD

**Issue by supershuai** [amoblin/gReader#2]
求支持 关于android语音反馈的demo～

**Comment by amoblin** [comment]
友盟官网下载的里面就有啊：http://dev.umeng.com/feedback/android/integration

或者也可以去这里讨论： http://bbs.umeng.com/forum-feedback-1.html

**Comment by supershuai** [comment]
这些方式都尝试过了哦，没有任何反馈......
有没有开发umeng语音反馈RD的联系方式之类的，还是直接工程师之间的交流畅通些～～

**Comment by amoblin** [comment]
OK，你给我发个邮件，我帮你转给RD吧
